apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    labels:
      io.kompose.service: tensorflow-serving
    name: tensorflow-serving
  spec:
    ports:
    - name: "9000"
      port: 9000
      nodePort: 30900
      targetPort: 9000
    selector:
      io.kompose.service: tensorflow-serving
    type: NodePort

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: tensorflow-serving
  spec:
    selector:
      matchLabels:
        io.kompose.service: tensorflow-serving
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          io.kompose.service: tensorflow-serving
      spec:
        containers:
        - name: tensorflow-serving
          image: duc2495/tf-serving-server:latest
          env:
          - name: PORT
            value: "9000"
          - name: MODEL_NAME
            value: "cpu"
          - name: MODEL_PATH
            value: "/tmp/cpu_model/"
          command: ["bin/bash"]
          args: ["-c", "/run_server.sh"]
          ports:
          - containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
        restartPolicy: Always
kind: List
metadata: {}

